language: minimal
jobs:
  include:
    - stage: unit-test
      provider: script
      script:
        - ./scripts/unit-tests-user-auth.sh
        - ./scripts/unit-tests-user-auth.sh
        - ./scripts/unit-tests-files.sh
    - stage: integration-test
      provider: script
      script:
        - bash scripts/integration-tests.sh
    - stage: deploy
      provider: script
      script:
        - ./scripts/deploy-to-azure.sh
        - ./scripts/deploy-to-google.sh
stages:
  - name: unit-test
    if: type = pull_request
  - name: integration-test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master
